version: '{build}'

environment:
  WINFLEXBISON_ARCHIVE: winflexbison-2.5.16.zip
  PANDOC_VERSION: 2.2.2.1
  PANDOC_ARCHIVE: pandoc-%PANDOC_VERSION%-windows-x86_64.zip
  matrix:
    - PYTHON: "C:\\Python37-x64"
      CMAKE_GENERATOR: Visual Studio 15 2017 Win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - PYTHON: "C:\\Python36-x64"
      CMAKE_GENERATOR: Visual Studio 15 2017 Win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - PYTHON: "C:\\Python37"
      CMAKE_GENERATOR: Visual Studio 15 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - PYTHON: "C:\\Python36"
      CMAKE_GENERATOR: Visual Studio 15 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #- PYTHON: "C:\\Python36-x64"
    #  CMAKE_GENERATOR: Visual Studio 14 2015 Win64
    #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #- PYTHON: "C:\\Python36"
    #  CMAKE_GENERATOR: Visual Studio 14 2015
    #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

configuration:
  - Release

matrix:
  fast_finish: true

install:
  - appveyor DownloadFile "https://downloads.sourceforge.net/project/winflexbison/old_versions/%WINFLEXBISON_ARCHIVE%"
  - 7z x -y -owinflexbison\ "%WINFLEXBISON_ARCHIVE%" > nul
  - appveyor DownloadFile "https://github.com/jgm/pandoc/releases/download/%PANDOC_VERSION%/%PANDOC_ARCHIVE%"
  - 7z x -y "%PANDOC_ARCHIVE%" > nul
  - set Path=%CD%\winflexbison;%CD%\pandoc-%PANDOC_VERSION%;%PYTHON%\Scripts;%Path%

before_build:
  - cmd: '%PYTHON%\Scripts\pip install -r requirements.txt'

build_script:
  - cmd: '%PYTHON%\python setup.py build --with-unit-tests'
  - cmd: '%PYTHON%\python setup.py install'

test_script:
  - cmd: build\tests\cpp\%configuration%\yaramod_tests.exe
  - cmd: '%PYTHON%\Scripts\pytest -v tests\python'

after_test:
  - cmd: '%PYTHON%\python setup.py bdist_wheel'

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
