language: cpp

matrix:
  fast_finish: true
  include:
      - os: linux
        dist: xenial
        compiler: gcc-5
        addons:
          apt:
            packages:
              - build-essential
              - coreutils
              - gcc-5
              - g++-5
              - pandoc
              - python3.5
              - python3.5-venv
              - cmake
              - flex
              - bison
        env:
          - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && NPROC=$(nproc)"
      - os: osx
        osx_image: xcode8.3
        env:
          - MATRIX_EVAL="NPROC=$(sysctl -n hw.physicalcpu)"
      - os: windows
        dist: 1803-containers
        env:
            - PYTHON_VERSION: 3.7.2
            - PYTHON_PATH: /c/Python37:/c/Python37/Scripts
      - os: windows
        dist: 1803-containers
        env:
            - PYTHON_VERSION: 3.6.8
            - PYTHON_PATH: /c/Python36:/c/Python36/Scripts


install:
  # We need to install newer versions of Flex and Bison on MacOS X.
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install flex bison gnu-sed && brew upgrade python;
    elif [ "$TRAVIS_OS_NAME" = "windows" ]; then
      choco install python --version ${PYTHON_VERSION}
      choco install pandoc winflexbison3
      export PATH="${PYTHON_PATH}:/c/Program Files/CMake/bin:$PATH"
      export CMAKE_INCLUDE_PATH="/c/ProgramData/chocolatey/lib/winflexbison3/tools"
    fi

before_script:
  - eval "${MATRIX_EVAL}"
  # We need to use newer versions of Flex and Bison on MacOS X (the ones from Homebrew).
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export CMAKE_INCLUDE_PATH="/usr/local/opt/flex/include"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export CMAKE_LIBRARY_PATH="/usr/local/opt/flex/lib;/usr/local/opt/bison/lib"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH="/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:$PATH"; fi

script:
  - ./setup_env.sh
  - |
    if [ "$TRAVIS_OS_NAME" != "windows" ]; then
      source env/bin/activate
    else
      export PATH="$PWD/env/Scripts:$PATH"
    fi
  - python setup.py build --with-unit-tests
  - python setup.py install
  - |
    if [ "$TRAVIS_OS_NAME" != "windows" ]; then
      build/tests/cpp/yaramod_tests
    else
      build/tests/cpp/Release/yaramod_tests
    fi
  - pytest tests/python

branches:
  only:
    # Pushes and PRs to the master branch.
    - master
    # Version tags.
    - /^v?\d+\.\d+.*$/

notifications:
  email:
    on_success: never
