language: cpp

env:
  global:
    - PYPI_USERNAME: metthal
    - secure: bFGZZmCC0Qud0TdJ1yJ3j8M449fmKn/Yk/JrGA/jtbdTlVEEW6C+mHUICuTHgMH1YD7+y5SMMsT1aA0t7uLSLjdIYmwKLBpJoPgoDDIJ1TCTtZ81/xjDasSrf5uFADEuVfMdCp6xD/2LUPjLSg+upgZjYUWIgH8PiLzJCdACu3Kod+FbzlP5UKHbbSQjOaOcskDqrAcmQvoswCuoX8kQNWvlq+42cHkXFWPpY1C759u7pCpoiwEgTsIr0vzj0C2gErdrX0tUlIsHNqkosqg/1Ek0DTmyT4dN/0jKKOHAgdwiVZc4E/6ZXJ08xqJesUviXqv3jTkxZ1B2jsROlvJgYmduQIChqaKJJabGYivHYpZJ2po62pTztbzdQkYoYcdxv3IvBAS9EskDGXP8JybjC5OMP49h5ntD/5YHuu0sKxi7y2+B9EeGhQcDzyCWxbSoyKeGTRbFACcXqnlTR2OxM40+4aj4+A3g0HWzFZevSBXz2/6aQLnVud5qDzxMqT06e6Tv84lJNPOELkr396GmWnU2O0N8W+lxJMikrXA4V4D5HYOMT7bas4goe5M9NRokjw7DVvn9HUVVKe874JgcY3ACvd/29YMWQ7F6zxKO+p2aPB+ob1CvvLNlLMuWGuxIUg4oFmWRjDbnu7gYPMT+hjeF+lof+h7u2WSNVygSOEM=

matrix:
  fast_finish: true
  include:
      - os: linux
        dist: xenial
        compiler: gcc-5
        addons:
          apt:
            packages:
              - build-essential
              - coreutils
              - gcc-5
              - g++-5
              - pandoc
              - python3.5
              - python3.5-venv
              - cmake
              - flex
              - bison
        env:
          - MATRIX_EVAL: "CC=gcc-5 && CXX=g++-5 && NPROC=$(nproc)"
          - DEPLOY_TO_PYPI: true
      - os: osx
        osx_image: xcode8.3
        env:
          - MATRIX_EVAL: "NPROC=$(sysctl -n hw.physicalcpu)"
      - os: windows
        dist: 1803-containers
        env:
          - PYTHON_VERSION: 3.7.2
          - PYTHON_PATH: /c/Python37:/c/Python37/Scripts
          - DEPLOY_TO_PYPI: true
      - os: windows
        dist: 1803-containers
        env:
          - PYTHON_VERSION: 3.6.8
          - PYTHON_PATH: /c/Python36:/c/Python36/Scripts
          - DEPLOY_TO_PYPI: true


install:
  # We need to install newer versions of Flex and Bison on MacOS X.
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install flex bison gnu-sed && brew upgrade python;
    elif [ "$TRAVIS_OS_NAME" = "windows" ]; then
      choco install python --version ${PYTHON_VERSION}
      choco install pandoc winflexbison3
      export PATH="${PYTHON_PATH}:/c/Program Files/CMake/bin:$PATH"
      export CMAKE_INCLUDE_PATH="/c/ProgramData/chocolatey/lib/winflexbison3/tools"
    fi

before_script:
  - eval "${MATRIX_EVAL}"
  # We need to use newer versions of Flex and Bison on MacOS X (the ones from Homebrew).
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export CMAKE_INCLUDE_PATH="/usr/local/opt/flex/include"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export CMAKE_LIBRARY_PATH="/usr/local/opt/flex/lib;/usr/local/opt/bison/lib"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH="/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:$PATH"; fi

script:
  - ./setup_env.sh
  - source use_env.sh
  - python setup.py build --with-unit-tests
  - python setup.py install
  - |
    if [ "$TRAVIS_OS_NAME" != "windows" ]; then
      build/tests/cpp/yaramod_tests
    else
      build/tests/cpp/Release/yaramod_tests
    fi
  - pytest tests/python

deploy:
  provider: script
  skip_cleanup: true
  script: bash pypi_deploy.sh
  on:
    condition: $DEPLOY_TO_PYPI = true

branches:
  only:
    # Pushes and PRs to the master branch.
    - master
    # Version tags.
    - /^v?\d+\.\d+.*$/

notifications:
  email:
    on_success: never
